pipenv run isort miner --check-only
pipenv run flake8
pipenv run mypy .
miner/data.py: note: In member "__init__" of class "FacebookData":
miner/data.py:14: error: Incompatible default for argument "reader" (default
has type "None", argument has type "Callable[..., Any]")
                self, path: str, reader: Callable = None,
                                                    ^
miner/data.py:15: error: Incompatible default for argument "processors"
(default has type "None", argument has type "List[Callable[..., Any]]")
                processors: List[Callable] = None
                                             ^
miner/data.py: note: In member "reader" of class "FacebookData":
miner/data.py:38: error: Incompatible return value type (got
"Callable[..., Any]", expected "Union[Dict[Any, Any], List[Any]]")
            return utils.read_json if self._reader is None else self._read...
                   ^
miner/data.py:38: error: If condition is always false
            return utils.read_json if self._reader is None else self._read...
                                      ^
miner/data.py: note: In member "_get_data" of class "FacebookData":
miner/data.py:45: error: Argument 1 to "_read_data" of "FacebookData" has
incompatible type "Union[Dict[Any, Any], List[Any]]"; expected
"Callable[..., Any]"
            raw_data = self._read_data(self.reader, self.path)
                                       ^
miner/data.py: note: In member "_get_preprocessor" of class "FacebookData":
miner/data.py:53: error: Statement is unreachable
                self._register_processors(preprocessor)
                ^
miner/data.py:55: error: 'def (*Any, **Any) -> Any' object is not iterable
                for func, args, kwargs in processors:
                ^
miner/data.py:56: error: Cannot determine type of 'func'
                    preprocessor.register_command(func, *args, **kwargs)
                                                  ^
miner/data.py:56: error: Cannot determine type of 'args'
                    preprocessor.register_command(func, *args, **kwargs)
                                                         ^
miner/data.py:56: error: Cannot determine type of 'kwargs'
                    preprocessor.register_command(func, *args, **kwargs)
                                                                 ^
miner/data.py: note: In member "_get_dataframe" of class "FacebookData":
miner/data.py:64: error: Function is missing a type annotation for one or more
arguments
        def _get_dataframe(data, field: str = None, **kwargs) -> pd.DataFr...
        ^
miner/data.py:64: error: Incompatible default for argument "field" (default has
type "None", argument has type "str")
        def _get_dataframe(data, field: str = None, **kwargs) -> pd.DataFr...
                                              ^
miner/cli_adapters.py: note: In member "__init__" of class "MessagingAnalyzerManagerFacade":
miner/cli_adapters.py:12: error: Function is missing a type annotation for one
or more arguments
        def __init__(self, analyzer) -> None:
        ^
miner/cli_adapters.py: note: In member "__init__" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:43: error: Function is missing a type annotation for one
or more arguments
        def __init__(
        ^
miner/cli_adapters.py:47: error: Incompatible default for argument "channels"
(default has type "None", argument has type "str")
                channels: str = None,
                                ^
miner/cli_adapters.py:48: error: Incompatible default for argument
"participants" (default has type "None", argument has type "str")
                participants: str = None,
                                    ^
miner/cli_adapters.py:49: error: Incompatible default for argument "senders"
(default has type "None", argument has type "str")
                senders: str = None,
                               ^
miner/cli_adapters.py: note: In member "all_channels" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:129: error: Incompatible default for argument "name"
(default has type "None", argument has type "str")
        def all_channels(self, name: str = None) -> List[str]:
                                           ^
miner/cli_adapters.py: note: In member "ranking_by_statistic" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:141: error: Function is missing a type annotation for one
or more arguments
        def ranking_by_statistic(
        ^
miner/cli_adapters.py: note: In member "messages" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:218: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def messages(self, output: str = None) -> pd.Series:
                                         ^
miner/cli_adapters.py: note: In member "text" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:228: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def text(self, output: str = None) -> pd.Series:
                                     ^
miner/cli_adapters.py: note: In member "media" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:238: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def media(self, output: str = None) -> pd.Series:
                                      ^
miner/cli_adapters.py: note: In member "words" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:248: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def words(self, output: str = None) -> pd.Series:
                                      ^
miner/cli_adapters.py: note: In member "most_used_msgs" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:321: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def most_used_msgs(self, output: str = None) -> pd.Series:
                                               ^
miner/cli_adapters.py: note: In member "most_used_words" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:331: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def most_used_words(self, output: str = None) -> pd.Series:
                                                ^
miner/cli_adapters.py: note: In member "reacted_messages" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:341: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def reacted_messages(self, output: str = None) -> pd.DataFrame:
                                                 ^
miner/cli_adapters.py: note: In member "files" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:359: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def files(self, output: str = None) -> pd.Series:
                                      ^
miner/cli_adapters.py: note: In member "photos" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:369: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def photos(self, output: str = None) -> pd.Series:
                                       ^
miner/cli_adapters.py: note: In member "videos" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:379: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def videos(self, output: str = None) -> pd.Series:
                                       ^
miner/cli_adapters.py: note: In member "audios" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:389: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def audios(self, output: str = None) -> pd.Series:
                                       ^
miner/cli_adapters.py: note: In member "gifs" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:399: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
        def gifs(self, output: str = None) -> pd.Series:
                                     ^
miner/cli_adapters.py: note: In member "get_grouped_time_series_data" of class "MessagingAnalyzerFacade":
miner/cli_adapters.py:433: error: Incompatible default for argument "output"
(default has type "None", argument has type "str")
                self, timeframe: str = "y", output: str = None
                                                          ^
miner/person.py: note: In class "Person":
miner/person.py:18: error: Incompatible types in assignment (expression has
type "None", variable has type "bool")
        friend: bool = None
                       ^
miner/person.py:19: error: Incompatible types in assignment (expression has
type "None", variable has type "str")
        compact_name: str = None
                            ^
miner/person.py:21: error: Incompatible types in assignment (expression has
type "None", variable has type "str")
        thread_path: str = None
                           ^
miner/person.py:22: error: Incompatible types in assignment (expression has
type "None", variable has type "str")
        media_dir: str = None
                         ^
miner/person.py:23: error: Incompatible types in assignment (expression has
type "None", variable has type "List[str]")
        member_of: List[str] = None
                               ^
miner/friends.py: note: In member "__init__" of class "Friends":
miner/friends.py:15: error: Incompatible default for argument "reader" (default
has type "None", argument has type "Callable[..., Any]")
                self, path: str, reader: Callable = None,
                                                    ^
miner/friends.py:16: error: Incompatible default for argument "processors"
(default has type "None", argument has type "List[Callable[..., Any]]")
                processors: List[Callable] = None
                                             ^
miner/friends.py: note: In member "get" of class "Friends":
miner/friends.py:20: error: Function is missing a type annotation for one or
more arguments
        def get(self, sort="date", dates: bool = True, output: str = None)...
        ^
miner/friends.py:20: error: Incompatible default for argument "output" (default
has type "None", argument has type "str")
    ...get(self, sort="date", dates: bool = True, output: str = None) -> str:
                                                                ^
miner/friends.py: note: In member "_set_metadata" of class "Friends":
miner/friends.py:53: error: Function "collections.namedtuple" is not valid as a
type
        def _set_metadata(self, data: Dict) -> namedtuple:
                                               ^
miner/friends.py:53: note: Perhaps you need "Callable[...]" or a callback protocol?
miner/friends.py:55: error: Incompatible types in assignment (expression has
type "metadata@54", variable has type "NamedTuple")
            self._metadata = metadata(length=len(data.get("friends")),
                             ^
miner/friends.py:55: error: Argument 1 to "len" has incompatible type
"Optional[Any]"; expected "Sized"
            self._metadata = metadata(length=len(data.get("friends")),
                                                 ^
setup.py: note: In function "setup_package":
setup.py:6: error: Function is missing a return type annotation
    def setup_package():
    ^
setup.py:6: note: Use "-> None" if function does not return a value
setup.py:8: error: Argument 1 to "getfile" has incompatible type
"Optional[FrameType]"; expected
"Union[Module, Type[Any], MethodType, FunctionType, TracebackType, FrameType, CodeType, Callable[..., Any]]"
    ...    os.getcwd(), os.path.dirname(inspect.getfile(inspect.currentframe(...
                                                        ^
setup.py: note: At top level:
setup.py:35: error: Call to untyped function "setup_package" in typed context
        setup_package()
        ^
miner/profile_information.py: note: In member "name" of class "ProfileInformation":
miner/profile_information.py:22: error: Item "str" of
"Union[str, List[Any], Dict[Any, Any]]" has no attribute "get"
            return self.data.get("profile").get("name").get("full_name")
                   ^
miner/profile_information.py:22: error: Item "List[Any]" of
"Union[str, List[Any], Dict[Any, Any]]" has no attribute "get"
            return self.data.get("profile").get("name").get("full_name")
                   ^
miner/profile_information.py:22: error: Item "None" of "Optional[Any]" has no
attribute "get"
            return self.data.get("profile").get("name").get("full_name")
                   ^
miner/profile_information.py: note: In member "registration_timestamp" of class "ProfileInformation":
miner/profile_information.py:32: error: Item "str" of
"Union[str, List[Any], Dict[Any, Any]]" has no attribute "get"
                self.data.get("profile").get("registration_timestamp"))
                ^
miner/profile_information.py:32: error: Item "List[Any]" of
"Union[str, List[Any], Dict[Any, Any]]" has no attribute "get"
                self.data.get("profile").get("registration_timestamp"))
                ^
miner/profile_information.py:32: error: Item "None" of "Optional[Any]" has no
attribute "get"
                self.data.get("profile").get("registration_timestamp"))
                ^
miner/people.py: note: In member "__init__" of class "People":
miner/people.py:19: error: Function is missing a type annotation for one or
more arguments
        def __init__(self, **kwargs) -> None:
        ^
miner/people.py: note: In member "get" of class "People":
miner/people.py:28: error: Incompatible default for argument "output" (default
has type "None", argument has type "str")
        def get(self, output: str = None) -> str:
                                    ^
miner/people.py: note: In member "_get_data_from_source" of class "People":
miner/people.py:67: error: Function is missing a type annotation for one or
more arguments
        def _get_data_from_source(self, **kwargs) -> Dict[str, Person]:
        ^
miner/people.py:68: error: Need type annotation for 'data' (hint:
"data: Dict[<type>, <type>] = ...")
            data = {}
            ^
miner/people.py: note: In member "_unify_people" of class "People":
miner/people.py:83: error: Unsupported left operand type for + ("None")
                    other[name] = other.get(name) + person
                                  ^
miner/people.py:83: note: Left operand is of type "Optional[Person]"
miner/people.py: note: In member "__init__" of class "PeopleIterator":
miner/people.py:120: error: Function is missing a type annotation for one or
more arguments
        def __init__(self, container) -> None:
        ^
miner/app.py: note: In member "__init__" of class "App":
miner/app.py:23: error: Incompatible default for argument "path" (default has
type "None", argument has type "str")
        def __init__(self, path: str = None):
                                       ^
miner/app.py: note: In member "profile_information" of class "App":
miner/app.py:65: error: Incompatible return value type (got
"ProfileInformation", expected "Dict[str, str]")
            return ProfileInformation(self._path)
                   ^
miner/app.py: note: In member "_build_config" of class "App":
miner/app.py:80: error: Dict entry 0 has incompatible type "str":
"Dict[str, str]"; expected "str": "str"
            return {"profile": self.profile_information}
                    ^
miner/cli.py: note: In member "__init__" of class "CLI":
miner/cli.py:25: error: Function is missing a type annotation
        def __init__(self, app):
        ^
miner/cli.py: note: In member "friends" of class "CLI":
miner/cli.py:28: error: Function is missing a type annotation
        def friends(self, sort="date", dates=True, output=None):
        ^
miner/cli.py: note: In member "conversations" of class "CLI":
miner/cli.py:43: error: Function is missing a return type annotation
        def conversations(
        ^
miner/cli.py:46: error: Incompatible default for argument "channels" (default
has type "None", argument has type "str")
                channels: str = None,
                                ^
miner/cli.py:47: error: Incompatible default for argument "cols" (default has
type "None", argument has type "List[str]")
                cols: List[str] = None,
                                  ^
miner/cli.py:48: error: Incompatible default for argument "output" (default has
type "None", argument has type "str")
                output: str = None,
                              ^
miner/cli.py: note: In member "analyzer" of class "CLI":
miner/cli.py:65: error: Function is missing a type annotation for one or more
arguments
        def analyzer(
        ^
miner/cli.py:67: error: Incompatible default for argument "kind" (default has
type "None", argument has type "str")
                kind: str = None,
                            ^
miner/cli.py:68: error: Incompatible default for argument "channels" (default
has type "None", argument has type "str")
                channels: str = None,
                                ^
miner/cli.py:69: error: Incompatible default for argument "participants"
(default has type "None", argument has type "str")
                participants: str = None,
                                    ^
miner/cli.py:70: error: Incompatible default for argument "senders" (default
has type "None", argument has type "str")
                senders: str = None,
                               ^
miner/cli.py:86: error: Statement is unreachable
                return MessagingAnalyzerManagerFacade(self._app.analyzer)
                ^
miner/cli.py: note: In member "people" of class "CLI":
miner/cli.py:96: error: Function is missing a return type annotation
        def people(self):
        ^
miner/cli.py: note: At top level:
miner/cli.py:128: error: Call to untyped function "CLI" in typed context
            Fire(CLI(app), name="Facebook-Data-Miner")
                 ^
miner/__main__.py:15: error: Call to untyped function "CLI" in typed context
            Fire(CLI(app), name="Facebook-Data-Miner")
                 ^
Found 77 errors in 10 files (checked 13 source files)
